### ISSUE TITLE
Images not cropped on PHP 7.3 or 7.4

### ISSUE THREAD

**Issue by HashandSalt** [flokosiol/kirby-focus#51] opened 2020-04-20 21:36 UTC
Seems images dont get cropped, but the file name does get changed to what should be with the crop ratio and size as part of the filename, but image is the orginal. It is just being passed through to the media folder without getting manipulated. If I switch back to PHP 7.2, eveythings good.

Observered on Centos 7 using GD and current Kirby release (3.3.5).

**Comment by flokosiol** [comment] 2020-04-25 21:21
Thanks for reporting. I will have a look at this as soon as possible, but it may take some time because my spare time is limited at the moment. Thanks for your patience.

**Comment by flokosiol** [comment] 2020-04-26 21:15
Unfortunately I can't test it with PHP 7.4 at the moment, but **with 7.3 everything seem to work fine** for me.

MacOS 10.14.6 
PHP 7.3.15 with GD
Kirby 3.3.5 – fresh StarterKit, no other plugins
Focus (current master branch)

![kirby-focus-php-7-3](https://user-images.githubusercontent.com/11918336/80319927-7c562d00-8813-11ea-8287-be140ab1173e.png)

![gd](https://user-images.githubusercontent.com/11918336/80319968-b9222400-8813-11ea-8e72-340fb39d0c84.png)

**Comment by flokosiol** [comment] 2020-04-26 21:18
What happens when you disable Focus and use the default `crop()` method instead? Does this work with PHP 7.3 and 7.4 on your server? Please make sure to clear the `media` folder before testing.

**Comment by HashandSalt** [comment] 2020-04-26 21:28
Thanks for investigating. The standard crop method works, and i also flushed out the media folder. THe only thing that made it work on both my local machine (Valet) and on my VPS was switching back to 7.2. If I find any more clues, I will share them.

**Comment by flokosiol** [comment] 2020-04-26 22:05
Thanks for the quick reply. That's really strange!?

**Comment by medienbaecker** [comment] 2021-03-02 09:59
I have the same issue on PHP 7.4 with ImageMagick set as the thumbs driver. There are no errors but the images don't get cropped 🙁

**Comment by flokosiol** [comment] 2021-03-07 20:30
Thanks @medienbaecker. I will try to set up a test environment for PHP 7.4 and ImageMagick (currently I only use GD).

**Comment by flokosiol** [comment] 2021-03-07 21:17
🤔  Unfortunately in my test case everything works fine:

PHP Version 7.4.13
ImageMagick 7.0.10-48
Kirby 3.5.3.1 Starterkit

**Comment by medienbaecker** [comment] 2021-03-08 07:46
Thanks for testing it yourself. Testing locally works without any issues. I think this is a server-side issue so I'll report back if I ever find a solution.

**Comment by HashandSalt** [comment] 2021-03-08 07:57
Maybe the issue is the other way round...perhaps its not PHP 7.4 thats the issue at all, but rather certain ImageMagick versions in combination with PHP 7.4. I am running ImageMagick 7.0.10-62 Q16 x86_64 2021-02-07 locally, installed via Homebrew. When i have a minute i will check which version is on my hosting.

**Comment by flokosiol** [comment] 2021-11-29 21:15
I close this issue. I haven't been able to reproduce the error and to all appearances there are no new findings … I hope you could fix everything on your own :)

**Closed by flokosiol** 2021-11-29 21:15 UTC
Labels: unclear
